# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql_db
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     ports:
#       - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - llmapp-network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   web:
#     build: .
#     container_name: llm_flask_app
#     command: python3 main.py
#     depends_on:
#       db:
#         condition: service_healthy
#     volumes:
#       - .:/LLMAPP
#     ports:
#       - "5005:5005"
#     environment:
#       - FLASK_ENV=development
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_HOST=db  # Ensure this matches the service name of the MySQL container
#       - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass the OpenAI API key
#     networks:
#       - llmapp-network

# volumes:
#   db_data:

# networks:
#   llmapp-network:
#     driver: bridge






version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - llmapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: 194722437060.dkr.ecr.ap-southeast-2.amazonaws.com/cab432-assignmen1-llmapp:latest
    container_name: llm_flask_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=production
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - llmapp-network

volumes:
  db_data:

networks:
  llmapp-network:
    driver: bridge





